[package]
name = "tiny-web-render-engine"
version = "0.1.0"
authors = ["silan-liu <413769707@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
